openapi: 3.0.3
info:
  title: Catalog Repository API
  description: Catalog Repository service REST API specification. Catalog Repository service is intended to serve information about products.
  version: 1.0.0
servers:
  - url: 'https://'
    description: 'Dev Server'
security:
  - basicAuth: []
tags:
  - name: products
    description: Products management resources
paths:
  /products:
    options:
      summary: CORS support
      tags:
        - products
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: { }
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {"statusCode" : 200}
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: '{}'
      x-amazon-apigateway-auth: NONE
    get:
      summary: List products
      description: Returns list of producsts that can be filtered by a number of fields
      operationId: products-list
      tags:
        - products
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
        - name: page_token
          in: query
          schema:
            $ref: '#/components/schemas/PageToken'
      responses:
        200:
          description: 'Successfully returned products list'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
        401:
          description: 'Unauthorized Exception'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: never
        requestParameters:
          integration.request.querystring.page_size: method.request.querystring.page_size
          integration.request.querystring.page_token: method.request.querystring.page_token
          integration.request.header.Authorization: method.request.header.Authorization
          integration.request.header.origin: method.request.header.origin
        responseParameters:
          method.response.header.Access-Control-Allow-Origin: integration.response.header.Access-Control-Allow-Origin
        security:
          - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Error:
      type: object
      title: 'Error'
      description: 'Error Details'
      properties:
        code:
          type: string
          title: 'Code'
          description: 'Error internal code'
        message:
          type: string
          title: 'Message'
          description: 'Error message'

    PageToken:
      title: 'Page Token'
      description: 'Next Page Token'
      minLength: 3
      type: string

    ProductsList:
      type: object
      title: 'Products List'
      description: 'Product List Details'
      required:
        - items
      properties:
        page_token:
          $ref: '#/components/schemas/PageToken'
        items:
          title: 'Product Items'
          description: 'Current page with product items'
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Product'

    Product:
      type: object
      title: 'Product'
      description: 'Product Details'
      required:
        - sku
        - product_type
        - url
        - color_main
        - colors
        - layouts
      properties:
        sku:
          title: 'SKU'
          description: 'Product SKU'
          type: string
          minLength: 1
        title:
          title: 'Title'
          description: 'Product Title'
          type: string
        description:
          title: 'Description'
          description: 'Product Description'
          type: string
        product_type:
          title: 'Type'
          description: 'Product Type'
          type: string
        main_image:
          title: 'Main Image'
          description: 'Product Main Image URL'
          type: string
        url:
          title: 'URL'
          description: 'Product URL'
          type: string

        collections_lv1:
          title: 'Collections Level 1 (old)'
          description: 'Product Collections Level 1 (old)'
          deprecated: true
          type: array
          items:
            - type: string
              minLength: 1

        collections_lv2:
          title: 'Collections Level 2 (old)'
          description: 'Product Collections Level 2 (old)'
          deprecated: true
          type: array
          items:
            - type: string
              minLength: 1

        color_main:
          title: 'Main Color'
          description: 'Product Main Color'
          type: string
          minLength: 3
        colors:
          title: 'Colors'
          description: 'Product Colors'
          type: array
          minItems: 1
          items:
            - type: string
              minLength: 3

        wish_count:
          title: 'Wish Count'
          description: 'Product Wish Count'
          type: integer
          minimum: 0
        sales_7_days:
          title: '7 Days Sales'
          description: 'Product 7 Days Sales'
          type: integer
          minimum: 0
        sales_30_days:
          title: '30 Days Sales'
          description: 'Product 30 Days Sales'
          type: integer
          minimum: 0
        sales_90_days:
          title: '90 Days Sales'
          description: 'Product 90 Days Sales'
          type: integer
          minimum: 0
        sales_all_time:
          title: 'All Time Sales'
          description: 'Product All Time Sales'
          type: integer
          minimum: 0

        reviews_count:
          title: 'Reviews Count'
          description: 'Product Reviews Count'
          type: integer
          minimum: 0
        reviews_avg_rating:
          title: 'Reviews Average Rating'
          description: 'Product Reviews Average Rating'
          type: number
          format: float
          minimum: 0

        tags_auto:
          title: 'Automated Tags'
          description: 'Product Automated Tags'
          type: array
          items:
            - type: string
              minLength: 1

        clearance:
          title: 'Clearance'
          description: 'Is product on clearance sale'
          type: boolean

        layouts:
          type: array
          items:
            - type: object
              properties:
                name:
                  type: string
                  enum:
                    - '1 Horizontal'
                    - '1 Panoramic'
                    - '1 Square'
                    - '1 Vertical Wide'
                    - '1 Vertical'
                    - '2 Horizontal'
                    - '2 Square'
                    - '3 Bow Horizontal'
                    - '3 Horizontal'
                    - '3 Square'
                    - '3 Vertical Wide'
                    - '3 Vertical'
                    - '3 Wine'
                    - '4 Horizontal'
                    - '4 Mess'
                    - '4 Square'
                    - '4 Vertical Wide'
                    - '5 Horizontal'
                    - '5 Mess'
                    - '5 Star'
                    - '6 Horizontal'
                    - '6 Vertical'
                    - '7 Hexagon'
                    - 'Core Horizontal'
                    - 'Core Vertical'
                    - 'Floating Horizontal'
                    - 'Floating Panoramic'
                    - 'Floating Vertical Wide'
                    - 'Framed Horizontal'
                    - 'Framed Panoramic'
                    - 'Framed Vertical Wide'
                type:
                  type: string
                  enum:
                    - 'Canvas'
                    - 'Multiple'
                    - 'Framed Print'
                    - 'Framed Canvas'
                pieces:
                  type: integer
                  minimum: 1
                  maximum: 6
                shape:
                  type: string
                  enum:
                    - 'horizontal'
                    - 'vertical'
                    - 'square'
                    - 'panoramic'
                    - 'hexagon'
                link:
                  type: string
                sizes:
                  type: array
                  items:
                    - type: object
                      properties:
                        size:
                          type: string
                        size_name:
                          type: string
                      required:
                        - size
                        - size_name
                preview_images:
                  type: array
                  items:
                    - type: object
                      properties:
                        image_link:
                          type: string
                        empty_room_link:
                          type: string
                        room_type:
                          type: string
                        colors:
                          type: array
                          items:
                            - type: string
                        styles:
                          type: array
                          items:
                            - type: string
                        unique:
                          type: array
                          items:
                            - type: string
        rooms:
          type: array
          items:
            - type: object
              properties:
                name:
                  type: string
        styles:
          type: object
          properties:
            lv1:
              type: array
              items:
                - type: string
            lv2:
              type: array
              items:
                - type: string
        created_at:
          type: integer
        last_updated:
          type: integer
        published_at:
          type: integer
        shopify_id:
          type: integer
        square_image:
          type: string
        clearance_details:
          type: array
          items:
            - type: object
              properties:
                layout_name:
                  type: string
                variant:
                  type: string
                size:
                  type: string
                price:
                  type: string
                compare_at_price:
                  type: string
                quantity:
                  type: integer
                link:
                  type: string
        objectID:
          type: string


