openapi: 3.0.3
info:
  title: Catalog Repository API
  description: Catalog Repository service REST API specification. Catalog Repository service is intended to serve information about products.
  version: 1.0.0
servers:
  - url: 'https://'
    description: 'Dev Server'
security:
  - basicAuth: []
tags:
  - name: products
    description: Products management resources
paths:
  /products:
    options:
      summary: CORS support
      tags:
        - products
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: { }
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {"statusCode" : 200}
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: '{}'
      x-amazon-apigateway-auth: NONE
    get:
      summary: List products
      description: Returns list of producsts that can be filtered by a number of fields
      operationId: products-list
      tags:
        - products
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
        - name: page_token
          in: query
          schema:
            $ref: '#/components/schemas/PageToken'
      responses:
        200:
          description: 'Successfully returned products list'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
        401:
          description: 'Unauthorized Exception'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: never
        requestParameters:
          integration.request.querystring.page_size: method.request.querystring.page_size
          integration.request.querystring.page_token: method.request.querystring.page_token
          integration.request.header.Authorization: method.request.header.Authorization
          integration.request.header.origin: method.request.header.origin
        responseParameters:
          method.response.header.Access-Control-Allow-Origin: integration.response.header.Access-Control-Allow-Origin
        security:
          - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Error:
      type: object
      title: 'Error'
      description: 'Error Details'
      properties:
        code:
          type: string
          title: 'Code'
          description: 'Error internal code'
        message:
          type: string
          title: 'Message'
          description: 'Error message'

    PageToken:
      title: 'Page Token'
      description: 'Next Page Token'
      minLength: 3
      type: string

    ProductsList:
      type: object
      title: 'Products List'
      description: 'Product List Details'
      required:
        - items
      properties:
        page_token:
          $ref: '#/components/schemas/PageToken'
        items:
          title: 'Product Items'
          description: 'Current page with product items'
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Product'

    RoomType:
      title: 'Room Type'
      description: 'Supported Room Type'
      type: string
      enum:
        - 'bar'
        - 'bathroom'
        - 'bedroom'
        - 'cafe & restaurant'
        - 'dining room'
        - 'gym/sport rooms'
        - 'hallway'
        - 'home office & office'
        - 'home office'
        - 'kids & nursery'
        - 'kids room'
        - 'kitchen & cafe'
        - 'kitchen & dining room'
        - 'kitchen'
        - 'laundry room'
        - 'living room'
        - 'lobby'
        - 'man cave & bar'
        - 'mancave'
        - 'nursery'
        - 'office'
        - 'salon'
        - 'spa'
        - 'teenager'
        - 'wall'
    LayoutName:
      title: 'layout Name'
      description: 'Product Layout Name'
      type: string
      enum:
        - '1 Horizontal'
        - '1 Panoramic'
        - '1 Square'
        - '1 Vertical Wide'
        - '1 Vertical'
        - '2 Horizontal'
        - '2 Square'
        - '3 Bow Horizontal'
        - '3 Horizontal'
        - '3 Square'
        - '3 Vertical Wide'
        - '3 Vertical'
        - '3 Wine'
        - '4 Horizontal'
        - '4 Mess'
        - '4 Square'
        - '4 Vertical Wide'
        - '5 Horizontal'
        - '5 Mess'
        - '5 Star'
        - '6 Horizontal'
        - '6 Vertical'
        - '7 Hexagon'
        - 'Core Horizontal'
        - 'Core Vertical'
        - 'Floating Horizontal'
        - 'Floating Panoramic'
        - 'Floating Vertical Wide'
        - 'Framed Horizontal'
        - 'Framed Panoramic'
        - 'Framed Vertical Wide'

    Product:
      type: object
      title: 'Product'
      description: 'Product Details'
      required:
        - sku
        - product_type
        - url
        - color_main
        - colors
        - layouts
      properties:
        sku:
          title: 'SKU'
          description: 'Product SKU'
          type: string
          minLength: 1
        title:
          title: 'Title'
          description: 'Product Title'
          type: string
        description:
          title: 'Description'
          description: 'Product Description'
          type: string
        product_type:
          title: 'Type'
          description: 'Product Type'
          type: string
        main_image:
          title: 'Main Image'
          description: 'Product Main Image URL'
          type: string
        url:
          title: 'URL'
          description: 'Product URL'
          type: string

        collections_lv1:
          title: 'Collections Level 1 (old)'
          description: 'Product Collections Level 1 (old)'
          deprecated: true
          type: array
          items:
            type: string
            minLength: 1

        collections_lv2:
          title: 'Collections Level 2 (old)'
          description: 'Product Collections Level 2 (old)'
          deprecated: true
          type: array
          items:
            type: string
            minLength: 1

        color_main:
          title: 'Main Color'
          description: 'Product Main Color'
          type: string
          minLength: 3
        colors:
          title: 'Colors'
          description: 'Product Colors'
          type: array
          minItems: 1
          items:
            type: string
            minLength: 3

        wish_count:
          title: 'Wish Count'
          description: 'Product Wish Count'
          type: integer
          minimum: 0
        sales_7_days:
          title: '7 Days Sales'
          description: 'Product 7 Days Sales'
          type: integer
          minimum: 0
        sales_30_days:
          title: '30 Days Sales'
          description: 'Product 30 Days Sales'
          type: integer
          minimum: 0
        sales_90_days:
          title: '90 Days Sales'
          description: 'Product 90 Days Sales'
          type: integer
          minimum: 0
        sales_all_time:
          title: 'All Time Sales'
          description: 'Product All Time Sales'
          type: integer
          minimum: 0

        reviews_count:
          title: 'Reviews Count'
          description: 'Product Reviews Count'
          type: integer
          minimum: 0
        reviews_avg_rating:
          title: 'Reviews Average Rating'
          description: 'Product Reviews Average Rating'
          type: number
          format: float
          minimum: 0

        tags_auto:
          title: 'Automated Tags'
          description: 'Product Automated Tags'
          type: array
          items:
            type: string
            minLength: 1

        clearance:
          title: 'Clearance'
          description: 'Is product on clearance sale'
          type: boolean
        clearance_details:
          title: 'Clearance Details'
          description: 'Product Clearance Details'
          type: array
          items:
            title: 'Clearance Item'
            description: 'Product Clearance Item'
            type: object
            required:
              - layout_name
              - variant
              - size
              - price
              - quantity
              - url
            properties:
              layout_name:
                $ref: '#/components/schemas/LayoutName'
              variant:
                title: 'Item Variant'
                description: 'Clearance Item Variant'
                type: string
              size:
                title: 'Item Size'
                description: 'Clearance Item Size'
                type: string
              price:
                title: 'Item Price'
                description: 'Clearance Item Price'
                type: number
                minimum: 0
              compare_at_price:
                title: 'Item Old Price'
                description: 'Clearance Item Old Price'
                type: number
                minimum: 0
              quantity:
                title: 'Item Quantity'
                description: 'Clearance Item Quantity'
                type: integer
                minimum: 1
              url:
                title: 'Item URL'
                description: 'Clearance Item URL'
                type: string

        layouts:
          title: 'Layouts'
          description: 'Product Layouts'
          type: array
          items:
            title: 'Layout'
            description: 'Product Layout'
            type: object
            required:
              - type
              - pieces
              - shape
            properties:
              name:
                $ref: '#/components/schemas/LayoutName'
              type:
                title: 'Type'
                description: 'Layout Type'
                type: string
                enum:
                  - 'Canvas'
                  - 'Multiple'
                  - 'Framed Print'
                  - 'Framed Canvas'
              pieces:
                title: 'Pieces'
                description: 'Number of Pieces in Layout'
                type: integer
                minimum: 1
                maximum: 6
              shape:
                title: 'Shape'
                description: 'Layout Shape'
                type: string
                enum:
                  - 'horizontal'
                  - 'vertical'
                  - 'square'
                  - 'panoramic'
                  - 'hexagon'
              url:
                title: 'URL'
                description: 'Layout Shop URL'
                type: string
                minLength: 5
              sizes:
                title: 'Sizes'
                description: 'Layout Sizes'
                type: array
                items:
                  title: 'Layout Size'
                  description: 'Layout Size'
                  type: object
                  required:
                    - size
                  properties:
                    size:
                      title: 'Size'
                      description: 'Layout Dimensions Size'
                      type: string
                      minLength: 3
                    name:
                      title: 'Name'
                      description: 'Layout Size Name'
                      type: string
              previews:
                title: 'Previews'
                description: 'Layout Previews'
                type: array
                items:
                  title: 'Preview'
                  description: 'Layout Preview'
                  type: object
                  required:
                    - preview_url
                    - room_type
                    - styles
                    - colors
                  properties:
                    preview_url:
                      title: 'Preview URL'
                      description: 'Layout Preview URL'
                      type: string
                    empty_room_url:
                      title: 'Room Preview URL'
                      description: 'Empty Room Preview URL'
                      type: string
                    room_type:
                      $ref: '#/components/schemas/RoomType'
                    colors:
                      title: 'Colors'
                      description: 'Preview Colors'
                      type: array
                      items:
                        type: string
                        enum:
                          - 'b&w'
                          - 'black'
                          - 'blue'
                          - 'brown'
                          - 'gray'
                          - 'green'
                          - 'light blue'
                          - 'orange'
                          - 'pink'
                          - 'purple'
                          - 'red'
                          - 'vanilla'
                          - 'yellow'
                    styles:
                      title: 'Styles'
                      description: 'Preview Styles'
                      type: array
                      items:
                        type: string
                        enum:
                          - 'commercial'
                          - 'farmhouse'
                          - 'feminine'
                          - 'hipster'
                          - 'masculine'
                          - 'minimalist'
                          - 'modern'
                          - 'nautical'
                          - 'oriental'
                          - 'rustic'
                          - 'scandinavian'
                          - 'shabby chic'
                          - 'traditional'
                          - 'vintage'
                    unique:
                      title: 'Unique'
                      description: 'Preview Unique'
                      type: array
                      items:
                        type: string
                        enum:
                          - 'african'
                          - 'bizarre'
                          - 'bold color'
                          - 'casual'
                          - 'dark'
                          - 'festive'
                          - 'greenery'
                          - 'lights'
                          - 'musical'
                          - 'patio'
                          - 'pets'
                          - 'pop of color'
                          - 'sporty'
        square_image_url:
          title: 'Square Image URL'
          description: 'Product Square Image URL'
          type: string

        rooms:
          title: 'Rooms'
          description: 'Product Rooms'
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/RoomType'

        styles_lv1:
          title: 'Styles Level 1'
          description: 'Product Styles Level 1'
          type: array
          items:
            type: string
        styles_lv2:
          title: 'Styles Level 2'
          description: 'Product Styles Level 2'
          type: array
          items:
            type: string

        created_at:
          title: 'Created At'
          description: 'Product Creation Timestamp'
          type: integer
          format: int64
        last_updated_at:
          title: 'Updated At'
          description: 'Product Last Update Timestamp'
          type: integer
          format: int64
        published_at:
          title: 'Published At'
          description: 'Product Publishing Timestamp'
          type: integer
          format: int64

        shopify_id:
          title: 'Shopify Id'
          description: 'Product Shopify Id'
          type: integer
          format: int64
