openapi: 3.0.3

info:
  title: Room Previews Generator API
  description: |
    ### Required URL Parameters:
    - **sku**: The SKU of the product
    - **layout**: The layout of the product

    ### Optional URL Parameters:
    - **height**: Resulting image height (default is `1200`)
    - **width**: Resulting image width (default is `1200`)
    - **format**: Image format (default is `jpeg`)
    - **quality**: Compression quality from 1-100 (default is `70`)
    - **type**: Image type, one of `[room, corner, info, sc]` (default is `room`)
    - **index**: Index per type, such as `room index`, `info index`, or `size chart index`
    - **frame_color**: Frame color (default is `black`)
    - **frame_style**: For framed canvas layouts, default is `floating`. For framed prints, default is `modern`.

    _________________
    
    ## Room Type:
    - Default index is `0`, which shows the artwork on a plain white background.  
    - 5 total indexes representing 5 different rooms: `[0 - 4]`.
    
    ### Canvas:
    #### Examples:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27&index=2](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27&index=2)

    ### Framed Canvas:
    - When not specifying colors or styles, it defaults to `black` and `floating`.
    
    #### Examples:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=floating-2-core-horizontal&size=40x25&index=4](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=floating-2-core-horizontal&size=40x25&index=4)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=floating-2-core-horizontal&size=40x25&index=3&frame_color=white&frame_style=modern-deep](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=floating-2-core-horizontal&size=40x25&index=3&frame_color=white&frame_style=modern-deep)

    ### Framed Print:
    - When not specifying colors or styles, it defaults to `black` and `modern`.
    
    #### Examples:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=framed-2-core-horizontal&size=44x26&index=1](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=framed-2-core-horizontal&size=44x26&index=1&frame_style=classic&frame_color=gold)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=framed-2-core-horizontal&size=44x26&index=1&frame_style=classic&frame_color=gold](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=framed-2-core-horizontal&size=44x26&index=1&frame_style=classic&frame_color=gold)
    
    _________________

    ## Corner Type:
    - Index is not used here.
    
    #### Example:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27&type=corner](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=54x27&type=corner)
    
    _________________

    ## Size Chart Type:
    - Default index is `0`.  
    - 4 Total indexes: `[0 - 3]` (representing two available sizes per index).
    
    #### Examples:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=sc](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=sc)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=sc&index=2](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=sc&index=2)
    
    _________________

    ## Info Type:
    - Default index is `0`, representing the non-rotated artwork info.
    - The magnifying glass effect only applies to the non-rotated artwork info (index `0`).
    - Index `1` represents the rotated artwork info, for which `size` is irrelevant.
    
    #### Examples:  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=49x24&type=info](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=49x24&type=info)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=49x24&type=info&m_glass=true](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&size=49x24&type=info&m_glass=true)  
    [https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=info&index=1](https://images.elephantstock.net/previews?sku=ND1-ES-1U1&layout=5-mess&type=info&index=1)  

  version: 1.0.0


servers:
  - url: https://images.elephantstock.net
  
tags:
  - name: "API"

paths:
  /previews:
    get:
      summary: Retrieve or generate room previews
      operationId: getRoomPreview
      tags:
        - API
      description: |
        Retrieve the room preview image for the given SKU, layout, room, size, frame style, and frame color.
        Generates and caches the image if it doesn't already exist.
      parameters:
        - name: sku
          in: query
          required: true
          description: SKU
          schema:
            type: string
            minLength: 3
            default: ND1-ES-1U1
        - name: layout
          in: query
          required: true
          description: Product layout
          schema:
            type: string
            minLength: 3
            default: 5-mess
        - name: type
          in: query
          description: Image type
          schema:
            type: string
            enum:
              - room
              - corner
              - info
              - sc
            default: room
        - name: index
          in: query
          required: false
          description: Index per image type (room OR info OR size chart)
          schema:
            type: number
            minimum: 0
            maximum: 100
        - name: size
          in: query
          required: false
          description: Overall size (e.g., 52x26)
          schema:
            type: string
            minLength: 3
            pattern: "^[0-9]+x[0-9]+$"
            default: 54x27
        - name: width
          in: query
          required: false
          description: Output image width
          schema:
            type: number
            minimum: 100
            maximum: 2400
            default: 1200
        - name: height
          in: query
          required: false
          description: Output image height
          schema:
            type: number
            minimum: 100
            maximum: 2400
            default: 1200
        - name: frame_style
          in: query
          required: false
          description: Frame style
          schema:
            type: string
            minLength: 3
        - name: frame_color
          in: query
          required: false
          description: Frame color
          schema:
            type: string
            minLength: 3
        - name: quality
          in: query
          required: false
          description: Image Quality (1-100, default 70)
          schema:
            type: number
            minimum: 1
            maximum: 100
            default: 70
        - name: m_glass
          in: query
          required: false
          description: Should render magnifying glass effect or not
          schema:
            type: boolean
            default: false
        - name: format
          in: query
          required: false
          description: Output image format (webp, jpeg)
          schema:
            type: string
            enum:
              - jpeg
              - webp
            default: jpeg
      responses:
        '200':
           $ref: '#/components/responses/SuccessResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

components:
  responses:
    SuccessResponse:
      description: Successfully retrieved or generated the image
      content:
        image/jpeg:
          schema:
            type: string
            format: binary
    NotFoundResponse:
      description: Resource not found
