openapi: 3.0.3

info:
  title: Room Previews Generator API
  description: |
    Project responsible for room previews generation.

    **Example URLs**:
    - [https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&index=0&size=92x42&quality=47](https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&index=0&size=92x42&quality=47)
    - [https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&type=info&index=1](https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&type=info&index=1)
    - [https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&type=sc&index=0](https://images.dev.elephantstock.net/previews?sku=KAB-ES-CJU&layout=5-star&type=sc&index=0)


  version: 1.0.0

servers:
  - url: https://images.elephantstock.net
  
tags:
  - name: "API"

paths:
  /previews:
    get:
      summary: Retrieve or generate room previews
      operationId: getRoomPreview
      tags:
        - API
      description: |
        Retrieve the room preview image for the given SKU, layout, room, size, frame style, and frame color.
        Generates and caches the image if it doesn't already exist.
      parameters:
        - name: sku
          in: query
          required: true
          description: SKU
          schema:
            type: string
            minLength: 3
        - name: layout
          in: query
          required: true
          description: Product layout
          schema:
            type: string
            minLength: 3
        - name: type
          in: query
          description: Image type
          schema:
            type: string
            enum:
              - room
              - corner
              - info
              - sc
            default: room
        - name: index
          in: query
          required: false
          description: Index per image type (room OR corner OR info OR size chart)
          schema:
            type: number
            minimum: 0
            maximum: 100
        - name: size
          in: query
          required: false
          description: Overall size (e.g., 52x26)
          schema:
            type: string
            minLength: 3
            pattern: "^[0-9]+x[0-9]+$"
        - name: width
          in: query
          required: false
          description: Output image width
          schema:
            type: number
            minimum: 100
            maximum: 2400
        - name: height
          in: query
          required: false
          description: Output image height
          schema:
            type: number
            minimum: 100
            maximum: 2400
        - name: frame_style
          in: query
          required: false
          description: Frame style
          schema:
            type: string
            minLength: 3
        - name: frame_color
          in: query
          required: false
          description: Frame color
          schema:
            type: string
            minLength: 3
        - name: quality
          in: query
          required: false
          description: Image Quality (1-100, default 70)
          schema:
            type: number
            minimum: 1
            maximum: 100
            default: 70
        - name: m_glass
          in: query
          required: false
          description: Should render magnifying glass effect or not
          schema:
            type: boolean
            default: false
        - name: format
          in: query
          required: false
          description: Output image format (webp, jpeg)
          schema:
            type: string
            enum:
              - jpeg
              - webp
            default: jpeg
      responses:
        '200':
           $ref: '#/components/responses/SuccessResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

components:
  responses:
    SuccessResponse:
      description: Successfully retrieved or generated the image
      content:
        image/jpeg:
          schema:
            type: string
            format: binary
    NotFoundResponse:
      description: Resource not found
